version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: project_backend
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
      - ./backend/storage:/var/www/storage
      - ./backend/.env:/var/www/.env # Monta o arquivo .env do backend
    ports:
      - "9000:9000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: project_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:9000

  db:
    image: postgres:15
    container_name: project_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB=project_management
      POSTGRES_USER=postgres
      POSTGRES_PASSWORD=teste

volumes:
  db_data:
