version: '3.8'

services:
  backend:
    build: ./projectManagement/projectManagement
    container_name: backend
    restart: always
    working_dir: /var/www
    ports:
      - "8000:8000"
    env_file:
      - ./projectManagement/projectManagement/.env
    depends_on:
      - db
    networks:
      - app-network
    command: >
      sh -c "while ! nc -z db 5432; do sleep 1; done && php artisan migrate:fresh --seed && php artisan serve --host=0.0.0.0 --port=8000"


  frontend:
    build: ./project-management-front
    container_name: frontend
    restart: always
    working_dir: /app
    volumes:
      - ./project-management-front:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ./project-management-front/.env
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: teste
      POSTGRES_DB: project_management
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
